export const emojiIconMap: Record<string, string> = {
  // Core UI
  "⚡": "/assets/icons/lightning.svg",
  "📝": "/assets/icons/pencil.svg",
  "🤸": "/assets/icons/activity.svg",
  "🤸‍♂️": "/assets/icons/activity.svg",
  "🤸‍♀️": "/assets/icons/activity.svg",
  "🎯": "/assets/icons/target.svg",
  "📊": "/assets/icons/bar-chart.svg",
  "✅": "/assets/icons/check-circle.svg",
  "💡": "/assets/icons/lightbulb.svg",
  "🔥": "/assets/icons/flame.svg",
  "🎁": "/assets/icons/gift.svg",
  "💚": "/assets/icons/heart.svg",
  "❤️": "/assets/icons/heart.svg",
  "🎙️": "/assets/icons/mic.svg",
  "🎙": "/assets/icons/mic.svg",
  "🏋️": "/assets/icons/dumbbell.svg",
  "🏋": "/assets/icons/dumbbell.svg",
  "🏋️‍♂️": "/assets/icons/dumbbell.svg",
  "💪": "/assets/icons/dumbbell.svg",
  "🏆": "/assets/icons/trophy.svg",
  "🔒": "/assets/icons/lock.svg",
  "🔓": "/assets/icons/lock.svg",
  "👑": "/assets/icons/crown.svg",
  "🏅": "/assets/icons/award.svg",
  "⭐": "/assets/icons/star.svg",
  "🌟": "/assets/icons/star.svg",
  "🚀": "/assets/icons/rocket.svg",
  "🎉": "/assets/icons/star.svg",

  // Category / branch indicators
  "🔵": "/assets/icons/circle.svg",
  "🟢": "/assets/icons/circle.svg",

  // Exercise-specific
  "🚩": "/assets/icons/flag.svg",
  "🌊": "/assets/icons/waves.svg",
  "🦅": "/assets/icons/feather.svg",
  "🔄": "/assets/icons/rotate-ccw.svg",
  "📉": "/assets/icons/trending-down.svg",
  "📐": "/assets/icons/ruler.svg",
  "📦": "/assets/icons/package.svg",
  "💥": "/assets/icons/explosion.svg",
  "💎": "/assets/icons/gem.svg",
  "🏔️": "/assets/icons/mountain.svg",
  "🏔": "/assets/icons/mountain.svg",
  "🏹": "/assets/icons/arrow-right.svg",
  "🐉": "/assets/icons/sword.svg",
  "🔫": "/assets/icons/crosshair.svg",
  "🦵": "/assets/icons/footprints.svg",
  "💺": "/assets/icons/armchair.svg",
  "🙌": "/assets/icons/hands.svg",
};
